// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ayezayunrounkxnekubl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5ZXpheXVucm91bmt4bmVrdWJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5OTg2NTEsImV4cCI6MjA3MzU3NDY1MX0.eLGml1kYTD9qvYERB_1qSoHIQbdWgfFE2JBSbDbtHUY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});